name: SCA Dependency Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  dependency-check:
    name: OWASP Dependency-Check SCA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "juice-shop-security-lab"
          path: "."
          format: "ALL"
          out: "dependency-check-report"
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: dependency-check-report
